"""add image builds

Revision ID: 92c1f6db3fdc
Revises: b150fa2f9e67
Create Date: 2026-08-25 15:15:33.419646

"""

from typing import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "92c1f6db3fdc"
down_revision: str | Sequence[str] | None = "b150fa2f9e67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_builds",
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("cluster_id", sa.String(length=36), nullable=False),
        sa.Column("requested_by", sa.String(length=36), nullable=False),
        sa.Column("engine_version_id", sa.String(length=36), nullable=True),
        sa.Column("runtime", sa.String(length=32), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("image_repository", sa.String(length=512), nullable=False),
        sa.Column("image_tag", sa.String(length=128), nullable=False),
        sa.Column("source_repository", sa.String(length=512), nullable=False),
        sa.Column("source_ref", sa.String(length=128), nullable=False),
        sa.Column("namespace", sa.String(length=63), nullable=False),
        sa.Column("job_name", sa.String(length=63), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("log_text", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("release_notes", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["engine_version_id"],
            ["engine_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_name"),
    )
    op.create_index(op.f("ix_image_builds_cluster_id"), "image_builds", ["cluster_id"], unique=False)
    op.create_index(op.f("ix_image_builds_deleted_at"), "image_builds", ["deleted_at"], unique=False)
    op.create_index("ix_image_builds_org_created_at", "image_builds", ["org_id", "created_at"], unique=False)
    op.create_index(op.f("ix_image_builds_org_id"), "image_builds", ["org_id"], unique=False)
    op.create_index(op.f("ix_image_builds_runtime"), "image_builds", ["runtime"], unique=False)
    op.create_index(
        "uq_image_builds_active_reference",
        "image_builds",
        ["image_repository", "image_tag"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND status IN ('pending', 'running')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_image_builds_active_reference",
        table_name="image_builds",
        postgresql_where=sa.text("deleted_at IS NULL AND status IN ('pending', 'running')"),
    )
    op.drop_index(op.f("ix_image_builds_runtime"), table_name="image_builds")
    op.drop_index(op.f("ix_image_builds_org_id"), table_name="image_builds")
    op.drop_index("ix_image_builds_org_created_at", table_name="image_builds")
    op.drop_index(op.f("ix_image_builds_deleted_at"), table_name="image_builds")
    op.drop_index(op.f("ix_image_builds_cluster_id"), table_name="image_builds")
    op.drop_table("image_builds")
    # ### end Alembic commands ###
